package com.cooper.proxy.db;

// Generated 2016-12-23 11:22:46 by htoa Tools 1.0

import java.util.Date;

/**
 * HiDbThreadLog generated by ZZQ
 */
public class HiDbThreadLog implements java.io.Serializable {

	private String threadLogId;
	private String threadClassName;
	private Integer invokeTimes;
	private String averageInvokeTime;
	private Date lastInvokeDate;
	private String detailId;

	public HiDbThreadLog() {
	}

	public HiDbThreadLog(String threadLogId) {
		this.threadLogId = threadLogId;
	}

	public HiDbThreadLog(String threadLogId, String threadClassName, Integer invokeTimes, 
			String averageInvokeTime, Date lastInvokeDate, String detailId) {
		this.threadLogId = threadLogId;
		this.threadClassName = threadClassName;
		this.invokeTimes = invokeTimes;
		this.averageInvokeTime = averageInvokeTime;
		this.lastInvokeDate = lastInvokeDate;
		this.detailId = detailId;
	}

	public String getThreadLogId() {
		return this.threadLogId;
	}

	public void setThreadLogId(String threadLogId) {
		this.threadLogId = threadLogId;
	}

	public String getThreadClassName() {
		return this.threadClassName;
	}

	public void setThreadClassName(String threadClassName) {
		this.threadClassName = threadClassName;
	}

	public Integer getInvokeTimes() {
		return this.invokeTimes;
	}

	public void setInvokeTimes(Integer invokeTimes) {
		this.invokeTimes = invokeTimes;
	}

	public String getAverageInvokeTime() {
		return this.averageInvokeTime;
	}

	public void setAverageInvokeTime(String averageInvokeTime) {
		this.averageInvokeTime = averageInvokeTime;
	}

	public Date getLastInvokeDate() {
		return this.lastInvokeDate;
	}

	public void setLastInvokeDate(Date lastInvokeDate) {
		this.lastInvokeDate = lastInvokeDate;
	}

	public String getDetailId() {
		return this.detailId;
	}

	public void setDetailId(String detailId) {
		this.detailId = detailId;
	}

}